---
- name: Tap Homebrew repositories
  homebrew_tap: name={{ item }} state=present
  with_items:
    - homebrew/binary
    - homebrew/completions
    - homebrew/dupes
    - homebrew/versions

- name: Update and upgrade Homebrew
  shell: brew update && brew upgrade && brew cleanup

- name: Install libraries with Homebrew
  homebrew: name={{ item }} state=latest
  with_items:
    - awscli
    - bash
    - bash-completion
    - cloc
    - coreutils
    - curl
    - git
    - gnu-sed
    - leiningen
    - maven
    - openssl
    - packer
    - postgresql
    - protobuf
    - pv
    - ssh-copy-id
    - the_silver_searcher
    - tig
    - tmux
    - tree
    - unrar
    - vcprompt
    - vim
    - watch
    - wget
    - wrk

- name: Install aspell with Homebrew
  homebrew: name=aspell state=latest install_options=all

- name: Install emacs with Homebrew
  homebrew: name=emacs state=linked install_options=cocoa

- name: Install openssh with Homebrew
  homebrew: name=openssh state=latest install_options=with-keychain-support
