#!/bin/bash
t=$(mktemp /tmp/cover.XXXXXXX)                                                                                                                                
go test $COVERFLAGS -coverprofile=$t $@ && go tool cover -func=$t && unlink $t
